[package]
name = "margined_utils"
version = "0.1.0"
authors = ["Margined Protocol"]
edition = "2021"
description = "Common helpers for margin protocol contracts"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "1.0.1" }
cw20-base = { version = "1.0.1", features = ["library"] }
cw-controllers = "1.0.1"
cosmwasm-schema = { version = "1.1.9" }
cosmwasm-std = { version = "1.1.9" }
cosmwasm-storage = { version = "1.1.9" }
margined_common = { version = "0.1.0", path = "../margined_common"}
margined_perp = { version = "0.1.0", path = "../margined_perp"}


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = "0.16.2"
