[package]
name = "margined_common"
version = "0.1.0"
authors = ["Margined Protocol"]
edition = "2021"
description = "Common package used by all margined contracts"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "1.0.1" }
cw-utils = "1.0.1"
cosmwasm-std = { version = "1.1.9" }
cosmwasm-storage = { version = "1.1.9" }
cosmwasm-schema = "1.1.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }


